spring.config.import=optional:file:../.env[.properties]

# Spring configuration
spring.application.name=${APP_NAME:mini-workout-logger-backend}
server.port=${APP_PORT:9090}
spring.messages.basename=i18n/messages

# Database configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=${MIGRATIONS_UP:true}
liquibase.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
spring.liquibase.clear-checksums=true

# Swagger configuration
springdoc.swagger-ui.defaultModelsExpandDepth=-1
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}

# WGER API configuration.
com.mini.workout-logger.integration.wger.endpoint=https://wger.de/api/v2
com.mini.workout-logger.integration.wger.username=${WGER_API_USERNAME:M1ni-workout-logger}
com.mini.workout-logger.integration.wger.password=${WGER_API_PASSWORD:mini-workout-logger}
